### ISSUE TITLE
Construct a YML file to render in a dynamic table

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/Generate_documentation_Nuxt#3]
The creation of this .yml file can be based on a subset of this file
https://github.com/standards-hub/test/blob/main/ddf_sample.xml

**Comment by jpradocueva** [comment]
@ladyargas can you add a link to the table that is using .yml file? I don't know where to find this dynamic table.

**Comment by ladyvargas** [comment]
@jpradocueva  Este es el link con el repositorio y el código listo para consumir YML, JSON y XML. Solo falta el archivo YML que está construyendo @anthonyaveiga 
[https://standards-hub.github.io/dynamic_tables/](url)

**Comment by jpradocueva** [comment]
This issue is now tracked in https://github.com/standards-hub/dynamic_tables/issues/3
